language: ruby
rvm:
  - 2.3.0
script: bundle exec rake
before_install:
  - openssl aes-256-cbc -K $encrypted_7e6f9cb1a6ae_key -iv $encrypted_7e6f9cb1a6ae_iv -in .env.enc -out .env -d
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  -  sleep 3 # give xvfb some time to start
  - 'bundle exec rake db:create db:migrate'
addons:
  postgresql: 9.3

